[build]
  command = "npm run build"
  publish="users/michaeldigiorgio/desktop/workspace/j9appCopy/build"
  base = "users/michaeldigiorgio/desktop/workspace/j9appCopy"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200